### ISSUE TITLE
Multiple relocations of same vault

### ISSUE THREAD

**Issue by iancoleman** [fizyk20/ageing_sim#2]
I've attached a log for a simulation I ran and am unsure about why the same vault is being relocated multiple times.

[20171213.log](https://github.com/fizyk20/ageing_sim/files/1553961/20171213.log)

```
$ grep "Relocating Node.9c15f7" 20171213.log 
Relocating Node(9c15f7...; age=1) from Prefix() to Prefix() as Node(0fbbad...; age=2)
Relocating Node(9c15f7...; age=1) from Prefix() to Prefix() as Node(5b9b63...; age=2)
Relocating Node(9c15f7...; age=1) from Prefix() to Prefix() as Node(650308...; age=2)
Relocating Node(9c15f7...; age=1) from Prefix() to Prefix() as Node(dfd395...; age=2)
Relocating Node(9c15f7...; age=1) from Prefix() to Prefix() as Node(ef927d...; age=2)
```

I would have expected after the first line to only see `0fbbad` mentioned and `9c15f7` never mentioned again, but `9c15f7` is relocated again 4 times in iteration 38.

All the new names (`0fbbad`, `5b9b63`, `650308`, etc) are also relocated later in the log.

Am I missing something? This seems like an error to me.

**Comment by fizyk20** [comment]
Huh... this is interesting. Thanks for the heads up, I'll definitely look into this!
